<a href="https://colab.research.google.com/github/DimitriBolt/Social-processes/blob/main/Investment_Market_Simulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Investment market simulation
------------------------------------

# Static Market model

## Agents

There are Acrots ☞ on the Market.

Each actor has its Capital

Agents| * | * | * |Capital|
-------------------|------------------|---| --- |---|
MorganStanley|*|*|*|\$1,000|
WarrenBuffett|*|*|*|\$100|
MS           |*|*|*|\$10
DB           |*|*|*|\$1

## Market companies

In [49]:
# @title
import numpy as np
# @title
import numpy as np
import pandas as pd
from numpy import ndarray

arr = np.array([[np.nan, np.nan, np.nan, np.nan],
                [np.nan, np.nan, np.nan, np.nan],
                [np.nan, np.nan, np.nan, np.nan],
                [np.nan, np.nan, np.nan, np.nan],
                [2200, 2600, 3000, 7800]
                ])
pd.DataFrame(data=arr,index=['*', '*', '*', '*', 'C:=Market Capitalization'] ,columns=['StartUp↗', "Star✩", 'Cash$Cow', '*'])

                          StartUp↗  Star✩  Cash$Cow    *
*                              NaN    NaN       NaN  NaN
*                              NaN    NaN       NaN  NaN
*                              NaN    NaN       NaN  NaN
*                              NaN    NaN       NaN  NaN
C:=Market Capitalization      2200   2600      3000 7800

each row of this table is a portfolio of the actor

In [50]:
# @title
import numpy as np
# @title
import numpy as np
import pandas as pd
arr = np.array(object=[[ 100,  200,  300,  600],
                       [ 400,  500,  600, 1500],
                       [ 700,  800,  900, 2400],
                       [1000, 1100, 1200, 3300],
                       [2200, 2600, 3000, 7800]
                       ],
               dtype=int)
pd.DataFrame(data=arr,index=['MorganStanley', 'WarrenBuffett', 'MS', 'DB', 'C = column Σ'] ,columns=['StartUp↗', "Star✩", 'Cash$Cow', 'capital of the actor = row Σ'])

               StartUp↗  Star✩  Cash$Cow  capital of the actor = row Σ
MorganStanley       100    200       300                           600
WarrenBuffett       400    500       600                          1500
MS                  700    800       900                          2400
DB                 1000   1100      1200                          3300
C = column Σ       2200   2600      3000                          7800

it was a state of a Market at time $t_0$

# Time dymamics

The Market capitalization growth $\frac{dC_i}{dt} (i \in \{StartUp↗, Star✩, Cash\$Cow\})$ depends on
- company size,
- market share.

## A dependency on company size

The simple formula of a dependency on company size derivers from empirical observations:
 - a "StartUp↗":  if company size = \$1,000 => it growths twice a year = +100%
 - a "Star✩"  : if company size = \\$1,000,000 => it growths on \$100,000 =  +10%
 - a "Cash\\$Cow": if company size = \\$1,000,000,000 => it growths on \$100,000,000 = +1%

so, an annual organic growth = $G_i =\frac{10}{\sqrt[3]{C_i}}$
$$\frac{C_i(t_1)}{C_i(t_o)} \propto [1+ G_i(t_0)]$$

## A dependency on company market share.
$$S_i = \frac{Market\ capitalization\ of\ a\ company}{whole\ market} = \frac{C_i}{M}$$

The closer a company gets to a monopoly position, the faster it tends to grow. The smaller the company, the harder it is to expand..
$$\frac{C_i(t_1)}{C_i(t_o)} \propto [1+ S_i(t_0)]$$

## Static market model at time $t_1$

$$C_i(t_1) = C_i(t_o)*[1+ S_i(t_0)]*[1+G_i(t_0)]$$

$$C_i(t_1) = C_i(t_o)*[1+ \frac{C_i(t_0)}{M(t_0)}]*[1+\frac{10}{\sqrt[3]{C_i(t_0)}}]$$

$$C_i(t_1) = C_i(t_o)*[1+ \frac{C_i(t_0)}{\sum_{j=1}^{\infty} C_j(t_0)}]*[1+\frac{10}{\sqrt[3]{C_i(t_0)}}]$$

# Agents' behaviour

At each step, for example from $t_0$ → $t_1$, there are two subSteps:

1. Each agent redistribute its portfolio
2. Capitalization of each company is changed under new market conditions.

## Portfolio management.

There are tons of simple well-known portfolio optimization models:
 - Markowitz model (simple mean-variance analysis - awarded a Nobel Memorial Prize in Economic Sciences)
 - Black–Litterman model
 - Linearly Constrained Quadratic Optimization in Portfolio Selection (case study from 589-course)

# Market simulation

In [51]:
import numpy as np
N_Steps = 300 # Number of iteration or number of periods.
market_simulation_array = np.empty((arr.shape[0], arr.shape[1], N_Steps - 1), dtype=arr.dtype) # let us to extent the market state at the first step to third dimention = time dimention.
market_simulation_array[:, :, 0] = arr # initial market state at step = 0

The initial market state at step = 0

In [52]:
pd.DataFrame(data=market_simulation_array[:, :, 0],index=['MorganStanley', 'WarrenBuffett', 'MS', 'DB', 'C = column Σ'] ,columns=['StartUp↗', "Star✩", 'Cash$Cow', 'capital of the actor = row Σ'])

               StartUp↗  Star✩  Cash$Cow  capital of the actor = row Σ
MorganStanley       100    200       300                           600
WarrenBuffett       400    500       600                          1500
MS                  700    800       900                          2400
DB                 1000   1100      1200                          3300
C = column Σ       2200   2600      3000                          7800

The function
```
market_capitalisation_performance(companies_capitalization: 'np.ndarray') -> 'np.ndarray':
```
calculates a growght of a market capitalization from current step to nect step.

In [53]:
import numpy as np


def market_capitalisation_performance(companies_capitalization: 'np.ndarray') -> 'np.ndarray':
    """
    Calculate the market capitalization performance based on the current market state.

    Parameters:
    current_market_state (np.ndarray): The current state of the market, including trader portfolios and companies capitalization.

    Returns:
    np.ndarray: An array representing the market capitalization performance for each company.
    """


    total_market_capitalization = np.sum(companies_capitalization)

    # Calculate market shares
    market_shares = companies_capitalization / total_market_capitalization

    company_growth_factor = 1 + 10 / (companies_capitalization ** (1 / 3))/10

    # Calculate market capitalization performance
    market_capitalization_performance = (1 + market_shares/10) * company_growth_factor

    return market_capitalization_performance

def trader_portfolios(market_capitalization_performance: 'np.ndarray',
                      trader_portfolios: 'np.ndarray') -> 'np.ndarray':
    """
    Redistribute each trader's capital to the best performing company.

    Parameters:
    market_capitalization_performance (np.ndarray): The performance of each company's market capitalization.
    trader_portfolios (np.ndarray): The current portfolios of traders.

    Returns:
    np.ndarray: Updated trader portfolios after redistribution.
    """

    # Find the indexes of the companies with the biggest performance
    best_companies_indexes: list = np.argwhere(market_capitalization_performance == np.max(market_capitalization_performance)).flatten().tolist()

    # Redistribute each trader's capital to the best performing company
    new_trader_portfolios = np.ones_like(trader_portfolios)
    trader_capitals_except_reminder = trader_portfolios.sum(axis=1) - (3-len(best_companies_indexes))
    trader_capitals_except_reminder = trader_capitals_except_reminder.reshape(-1, 1)  # Reshape to allow broadcasting
    # Each trader invests all their capital in the best performing companies.
    new_trader_portfolios[:, best_companies_indexes] = trader_capitals_except_reminder  // len(best_companies_indexes)

    return new_trader_portfolios

In [54]:
arr = np.array(object=[[100, 200, 300],
                       [400, 500, 600],
                       [700, 800, 900],
                       [1000, 1100, 1200]
                       ],
               dtype=np.int64)
N_Steps = 300
np.random.seed(0)  # Set a specific seed value (e.g., 0) for reproducibility
market_simulation_array = np.empty((arr.shape[0], arr.shape[1], N_Steps), dtype=arr.dtype) # market_simulation_array.ndim = 3, where the first two dimensions are for companies and traders, and the third dimension is for time steps.
market_simulation_array[:, :, 0] = arr #

# This code simulates a market with economic agents (traders) and companies.
for step in range(N_Steps-1):
    market_state_initial = market_simulation_array[:, :, step] # ndim = 2, where the first dimension is for traders and the second dimension is for companies.

    # Block 1. Calculation a potential market capitalization performance, based on the current companies' capitalization.
    companies_capitalization_initial = market_state_initial.sum(axis=0) # sum of each column. ndim = 1, where the first dimension is for companies.
    market_capitalization_performance_initial = market_capitalisation_performance(companies_capitalization_initial) # ndim= 1, where the first dimension is for companies.

    # Block 2.Redistribute each trader's capital to the best performing company. Or use any other strategy.
    trader_portfolios_initial = market_state_initial # ndim = 2, where the first dimension is for traders and the second dimension is for companies.
    trader_portfolios_after_redistribution = trader_portfolios(market_capitalization_performance_initial, trader_portfolios_initial)

    # Block 3. Calculate the new market capitalization performance based on the new trader portfolios.
    companies_capitalization_after_redistribution = trader_portfolios_after_redistribution.sum(axis=0) # sum of each column. ndim = 1, where the first dimension is for companies.
    market_capitalization_performance_after_redistribution = market_capitalisation_performance(companies_capitalization_after_redistribution)

    # Block 4. Update the market state taking into account the new trader portfolios and the new market capitalization performance.
    market_state_before_random = trader_portfolios_after_redistribution * market_capitalization_performance_after_redistribution

    # Block 5. Introduce randomness in the total market capitalization while preserving relative shares within each company.
    companies_capitalization_before_randomness = market_state_before_random.sum(axis=0) # sum of each column.
    std_dev: ndarray = np.power(companies_capitalization_before_randomness, 0.75) # Standard deviation based on company size.
    # Introduce randomness to the market state.
    companies_capitalization_after_randomness = np.random.normal(loc=companies_capitalization_before_randomness, scale=std_dev)
    market_state_after_randomness = market_state_before_random * (companies_capitalization_after_randomness / companies_capitalization_before_randomness)

    # Block 6. Update the market simulation array with the new market state after randomness.
    # if any element of market_state_after_randomness < 1, then set it to 1.
    market_state_after_randomness[market_state_after_randomness < 1] = 1
    market_simulation_array[:, :, step + 1] = market_state_after_randomness
    pass

## Capitalization of each compaies by time.
Due to each agent withdraws all thier capital from not most profitable companies and puts the capital to the most profitable company (exept minimu reminder =\$1), we can see oscilations from a minimum (=4 * \$1) to maximum.

In [57]:
companies_capitalization_by_time = market_simulation_array[:, :, ].sum(axis=0).transpose()
pd.DataFrame(data=companies_capitalization_by_time, columns=['StartUp↗', "Star✩", 'Cash$Cow'])

             StartUp↗            Star✩         Cash$Cow
0                2200             2600             3000
1                  12                8             9905
2                  12            13475                4
3                   8                4            15309
4                   8            17739               12
..                ...              ...              ...
295   772204515084758                4                4
296                 4  405497540528277  405365446799015
297   892003110086228                4                4
298                 8  468401426021640  468290113093766
299  1030112628549814               12                4

[300 rows x 3 columns]

Due to each agent nkows market-rule-of-motion, it can put capital to most profitable company, therefore we can exponential growght.

In [56]:
traders_capital_by_time = market_simulation_array.sum(axis=1)
pd.DataFrame(data=traders_capital_by_time,index=['MorganStanley', 'WarrenBuffett', 'MS', 'DB'])

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
MorganStanley,600,765,1040,1181,1370,1665,2123,2087,2527,2877,...,40550223553564,44615632940906,46845092832416,51527955885155,54107394913406,59519480348227,62499173077269,68753238998488,72197704838088,79398355168515
WarrenBuffett,1500,1909,2595,2947,3416,4150,5292,5201,6298,7169,...,101170588205340,111313562102133,116875942499531,128559429494488,134994988681560,148497845605029,155932015867252,171535568017562,180129321750765,198094550189714
MS,2400,3053,4150,4713,5463,6637,8464,8320,10074,11466,...,161842759968585,178068492356486,186966641625747,205656735405603,215951710252078,237552253164014,249444707825566,274405736422084,288153178710836,316892184835070
DB,3300,4198,5706,6480,7510,9124,11636,11439,13851,15765,...,222534195466637,244844617653575,257079594918927,282778520118323,296934136009046,326634935967496,342987090557209,377308566648102,396211333815725,435727538356531

TODO
- Бифуркации. Logistic map.
- Добавить случайности.
    - чем меньше компания, тем больше σ².
    - У маленьких компаний
$\mathbb{E}[\frac{dC_i}{dt}] <0$  
    - У больших компаний
$0 < \mathbb{E}[\frac{dC_i}{dt}] << 1 $

- Каждый агент имеет свою Стратегию работы с каждым рыночным сегментом. Много разных инвесторов - много стратегий.

- Агент может менять стратегию в зависимости от рыночной ситуации.