<a href="https://colab.research.google.com/github/DimitriBolt/Social-processes/blob/main/Investment_Market_Simulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Investment market simulation
------------------------------------

# Static Market model

## Agents

There are Acrots ☞ on the Market.

Each actor has its Capital

Agents| * | * | * |Capital|
-------------------|------------------|---| --- |---|
MorganStanley|*|*|*|\$1,000|
WarrenBuffett|*|*|*|\$100|
MS           |*|*|*|\$10
DB           |*|*|*|\$1

## Market companies

In [ ]:
# @title
import numpy as np
# @title
import numpy as np
import pandas as pd
arr = np.array([[np.nan, np.nan, np.nan, np.nan],
                [np.nan, np.nan, np.nan, np.nan],
                [np.nan, np.nan, np.nan, np.nan],
                [np.nan, np.nan, np.nan, np.nan],
                [2200, 2600, 3000, 7800]
                ])
pd.DataFrame(data=arr,index=['*', '*', '*', '*', 'C:=Market Capitalization'] ,columns=['StartUp↗', "Star✩", 'Cash$Cow', '*'])

                          StartUp↗   Star✩  Cash$Cow       *
*                              NaN     NaN       NaN     NaN
*                              NaN     NaN       NaN     NaN
*                              NaN     NaN       NaN     NaN
*                              NaN     NaN       NaN     NaN
C:=Market Capitalization    2200.0  2600.0    3000.0  7800.0

each row of this table is a portfolio of the actor

In [ ]:
# @title
import numpy as np
# @title
import numpy as np
import pandas as pd
arr = np.array(object=[[ 100,  200,  300,  600],
                       [ 400,  500,  600, 1500],
                       [ 700,  800,  900, 2400],
                       [1000, 1100, 1200, 3300],
                       [2200, 2600, 3000, 7800]
                       ],
               dtype=int)
pd.DataFrame(data=arr,index=['MorganStanley', 'WarrenBuffett', 'MS', 'DB', 'C = column Σ'] ,columns=['StartUp↗', "Star✩", 'Cash$Cow', 'capital of the actor = row Σ'])

               StartUp↗  Star✩  Cash$Cow  capital of the actor = row Σ
MorganStanley       100    200       300                           600
WarrenBuffett       400    500       600                          1500
MS                  700    800       900                          2400
DB                 1000   1100      1200                          3300
C = column Σ       2200   2600      3000                          7800

it was a state of a Market at time $t_0$

# Time dymamics

The Market capitalization growth $\frac{dC_i}{dt} (i \in \{StartUp↗, Star✩, Cash\$Cow\})$ depends on
- company size,
- market share.

## A dependency on company size

The simple formula of a dependency on company size derivers from empirical observations:
 - a "StartUp↗":  if company size = \$1,000 => it growths twice a year = +100%
 - a "Star✩"  : if company size = \\$1,000,000 => it growths on \$100,000 =  +10%
 - a "Cash\\$Cow": if company size = \\$1,000,000,000 => it growths on \$100,000,000 = +1%

so, an annual organic growth = $G_i =\frac{10}{\sqrt[3]{C_i}}$
$$\frac{C_i(t_1)}{C_i(t_o)} \propto [1+ G_i(t_0)]$$

## A dependency on company market share.
$$S_i = \frac{Market\ capitalization\ of\ a\ company}{whole\ market} = \frac{C_i}{M}$$

The closer a company gets to a monopoly position, the faster it tends to grow. The smaller the company, the harder it is to expand..
$$\frac{C_i(t_1)}{C_i(t_o)} \propto [1+ S_i(t_0)]$$

## Static market model at time $t_1$

$$C_i(t_1) = C_i(t_o)*[1+ S_i(t_0)]*[1+G_i(t_0)]$$

$$C_i(t_1) = C_i(t_o)*[1+ \frac{C_i(t_0)}{M(t_0)}]*[1+\frac{10}{\sqrt[3]{C_i(t_0)}}]$$

$$C_i(t_1) = C_i(t_o)*[1+ \frac{C_i(t_0)}{\sum_{j=1}^{\infty} C_j(t_0)}]*[1+\frac{10}{\sqrt[3]{C_i(t_0)}}]$$

# Agents' behaviour

At each step, for example from $t_0$ → $t_1$, there are two subSteps:

1. Each agent redistribute its portfolio
2. Capitalization of each company is changed under new market conditions.

## Portfolio management.

There are tons of simple well-known portfolio optimization models:
 - Markowitz model (simple mean-variance analysis - awarded a Nobel Memorial Prize in Economic Sciences)
 - Black–Litterman model
 - Linearly Constrained Quadratic Optimization in Portfolio Selection (case study from 589-course)

# Market simulation

In [ ]:
import numpy as np
N_Steps = 300 # Number of iteration or number of periods.
market_simulation_array = np.empty((arr.shape[0], arr.shape[1], N_Steps - 1), dtype=arr.dtype) # let us to extent the market state at the first step to third dimention = time dimention.
market_simulation_array[:, :, 0] = arr # initial market state at step = 0

The inital market state at step = 0

In [ ]:
pd.DataFrame(data=market_simulation_array[:, :, 0],index=['MorganStanley', 'WarrenBuffett', 'MS', 'DB', 'C = column Σ'] ,columns=['StartUp↗', "Star✩", 'Cash$Cow', 'capital of the actor = row Σ'])

               StartUp↗  Star✩  Cash$Cow  capital of the actor = row Σ
MorganStanley       100    200       300                           600
WarrenBuffett       400    500       600                          1500
MS                  700    800       900                          2400
DB                 1000   1100      1200                          3300
C = column Σ       2200   2600      3000                          7800

The function
```
market_capitalisation_performance(companies_capitalization: 'np.ndarray') -> 'np.ndarray':
```
calculates a growght of a market capitalization from current step to nect step.

In [ ]:
import numpy as np


def market_capitalisation_performance(companies_capitalization: 'np.ndarray') -> 'np.ndarray':
    """
    Calculate the market capitalization performance based on the current market state.

    Parameters:
    current_market_state (np.ndarray): The current state of the market, including trader portfolios and companies capitalization.

    Returns:
    np.ndarray: An array representing the market capitalization performance for each company.
    """


    total_market_capitalization = np.sum(companies_capitalization)

    # Calculate market shares
    market_shares = companies_capitalization / total_market_capitalization

    company_growth_factor = 1 + 10 / (companies_capitalization ** (1 / 3))/10

    # Calculate market capitalization performance
    market_capitalization_performance = (1 + market_shares/10) * company_growth_factor

    return market_capitalization_performance

def trader_portfolios(market_capitalization_performance: 'np.ndarray',
                      trader_portfolios: 'np.ndarray') -> 'np.ndarray':
    """
    Redistribute each trader's capital to the best performing company.

    Parameters:
    market_capitalization_performance (np.ndarray): The performance of each company's market capitalization.
    trader_portfolios (np.ndarray): The current portfolios of traders.

    Returns:
    np.ndarray: Updated trader portfolios after redistribution.
    """

    # Find the indexes of the companies with the biggest performance
    best_companies_indexes: list = np.argwhere(market_capitalization_performance == np.max(market_capitalization_performance)).flatten().tolist()

    # Redistribute each trader's capital to the best performing company
    new_trader_portfolios = np.ones_like(trader_portfolios)
    trader_capitals_except_reminder = trader_portfolios.sum(axis=1) - (3-len(best_companies_indexes))
    trader_capitals_except_reminder = trader_capitals_except_reminder.reshape(-1, 1)  # Reshape to allow broadcasting
    # Each trader invests all their capital in the best performing companies.
    new_trader_portfolios[:, best_companies_indexes] = trader_capitals_except_reminder  // len(best_companies_indexes)

    return new_trader_portfolios

In [ ]:
arr = np.array(object=[[100, 200, 300],
                       [400, 500, 600],
                       [700, 800, 900],
                       [1000, 1100, 1200]
                       ],
               dtype=np.int64)
N_Steps = 300
market_simulation_array = np.empty((arr.shape[0], arr.shape[1], N_Steps), dtype=arr.dtype)
market_simulation_array[:, :, 0] = arr

# This code simulates a market with economic agents (traders) and companies.
for step in range(N_Steps-1):
    current_market_state = market_simulation_array[:, :, step]

    # Block 1. Calculation a potential market capitalization performance, based on the current companies' capitalization.
    companies_capitalization = current_market_state.sum(axis=0) # sum of each column.
    initial_market_capitalization_performance: np.ndarray = market_capitalisation_performance(companies_capitalization)

    # Block 2.Redistribute each trader's capital to the best performing company. Or use any other strategy.
    current_trader_portfolios = current_market_state
    new_trader_portfolios = trader_portfolios(initial_market_capitalization_performance, current_trader_portfolios)

    # Block 3. Calculate the new market capitalization performance based on the new trader portfolios.
    new_companies_capitalization = new_trader_portfolios.sum(axis=0)
    actual_market_capitalization_performance: np.ndarray = market_capitalisation_performance(new_companies_capitalization)

    # Block 4. Update the market state taking into account the new trader portfolios and the new market capitalization performance.
    next_market_state = new_trader_portfolios * actual_market_capitalization_performance

    # Block 5. Introduce randomness in the total market capitalization while preserving relative shares within each company.
    total_market_capitalization = np.sum(next_market_state)
    std_dev = total_market_capitalization / 3
    random_factor = np.random.normal(loc=total_market_capitalization, scale=std_dev)
    # Ensure random_factor is not negative
    random_factor = max(0.1, random_factor)

    scaling_factor = random_factor / total_market_capitalization
    next_market_state = next_market_state * scaling_factor

    market_simulation_array[:, :, step + 1] = next_market_state

/tmp/ipython-input-2427939263.py:21: RuntimeWarning: divide by zero encountered in divide
  company_growth_factor = 1 + 10 / (companies_capitalization ** (1 / 3))/10

## Capitalization of each compaies by time.
Due to each agent withdraws all thier capital from not most profitable companies and puts the capital to the most profitable company (exept minimu reminder =\$1), we can see oscilations from a minimum (=4 * \$1) to maximum.

In [ ]:
companies_capitalization_by_time = market_simulation_array[:, :, ].sum(axis=0).transpose()
pd.DataFrame(data=companies_capitalization_by_time, columns=['StartUp↗', "Star✩", 'Cash$Cow'])

     StartUp↗   Star✩  Cash$Cow
0        2200    2600      3000
1           8       8     11527
2        6024    6024         4
3           4       4     13840
4        3790    3790         0
..        ...     ...       ...
295         4       4    389685
296    289400  289400         8
297         4       4    517587
298    227040  227040         4
299         8       8    677821

[300 rows x 3 columns]

Due to each agent nkows market-rule-of-motion, it can put capital to most profitable company, therefore we can exponential growght.

In [ ]:
traders_capital_by_time = market_simulation_array.sum(axis=1)
pd.DataFrame(data=traders_capital_by_time,index=['MorganStanley', 'WarrenBuffett', 'MS', 'DB'])

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
MorganStanley,600,888,925,1062,580,1089,66,94,180,284,...,7139,7366,9235,16591,8014,10235,15202,13594,11925,17802
WarrenBuffett,1500,2220,2317,2662,1456,2733,168,241,470,741,...,47623,49139,61629,110722,53494,68322,101478,90746,79611,118840
MS,2400,3552,3709,4262,2334,4382,270,388,754,1189,...,88459,91276,114475,205664,99366,126910,188498,168563,147881,220750
DB,3300,4883,5101,5862,3210,6026,370,533,1040,1639,...,128407,132496,166173,298544,144242,184226,273630,244692,214667,320445

TODO
- Бифуркации. Logistic map.
- Добавить случайности.
    - чем меньше компания, тем больше σ².
    - У маленьких компаний
$\mathbb{E}[\frac{dC_i}{dt}] <0$  
    - У больших компаний
$0 < \mathbb{E}[\frac{dC_i}{dt}] << 1 $

- Каждый агент имеет свою Стратегию работы с каждым рыночным сегментом. Много разных инвесторов - много стратегий.

- Агент может менять стратегию в зависимости от рыночной ситуации.